import type { InsertExercise } from "../../shared/schema.js";

export const SEED_EXERCISES: InsertExercise[] = [
  // Chest
  { name: "Barbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Front Delts"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Incline Barbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Front Delts"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Dumbbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Front Delts"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Incline Dumbbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Front Delts"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Cable Fly", primaryMuscle: "Chest", secondaryMuscles: [], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Dumbbell Fly", primaryMuscle: "Chest", secondaryMuscles: [], category: "isolation", equipment: "dumbbell", isCustom: false },
  { name: "Push-Up", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Front Delts"], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Chest Dip", primaryMuscle: "Chest", secondaryMuscles: ["Triceps"], category: "compound", equipment: "bodyweight", isCustom: false },
  { name: "Bench Press (Smith Machine)", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Front Delts"], category: "compound", equipment: "smith_machine", isCustom: false },
  { name: "Incline Bench Press (Smith Machine)", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Front Delts"], category: "compound", equipment: "smith_machine", isCustom: false },
  { name: "Decline Barbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Decline Dumbbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Cable Crossover (High to Low)", primaryMuscle: "Chest", secondaryMuscles: [], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Cable Crossover (Low to High)", primaryMuscle: "Chest", secondaryMuscles: [], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Pec Deck Machine", primaryMuscle: "Chest", secondaryMuscles: [], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Machine Chest Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Front Delts"], category: "compound", equipment: "machine", isCustom: false },
  { name: "Lying Chest Press (Machine)", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Front Delts"], category: "compound", equipment: "machine", isCustom: false },
  // Back
  { name: "Barbell Deadlift", primaryMuscle: "Back", secondaryMuscles: ["Glutes", "Hamstrings", "Traps"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Barbell Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps", "Rear Delts"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Bent-Over Row (Smith Machine)", primaryMuscle: "Back", secondaryMuscles: ["Biceps", "Rear Delts"], category: "compound", equipment: "smith_machine", isCustom: false },
  { name: "Pull-Up", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], category: "compound", equipment: "bodyweight", isCustom: false },
  { name: "Lat Pulldown", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], category: "compound", equipment: "cable", isCustom: false },
  { name: "Seated Cable Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps", "Rear Delts"], category: "compound", equipment: "cable", isCustom: false },
  { name: "Dumbbell Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "T-Bar Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Face Pull", primaryMuscle: "Back", secondaryMuscles: ["Rear Delts", "External Rotators"], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Chin-Up", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], category: "compound", equipment: "bodyweight", isCustom: false },
  { name: "Pendlay Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps", "Rear Delts"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Chest-Supported Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps", "Rear Delts"], category: "compound", equipment: "machine", isCustom: false },
  { name: "Straight-Arm Pulldown", primaryMuscle: "Back", secondaryMuscles: ["Triceps"], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Rack Pull", primaryMuscle: "Back", secondaryMuscles: ["Glutes", "Hamstrings", "Traps"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Reverse Fly (Dumbbell)", primaryMuscle: "Back", secondaryMuscles: ["Rear Delts"], category: "isolation", equipment: "dumbbell", isCustom: false },
  { name: "Reverse Pec Deck Fly", primaryMuscle: "Back", secondaryMuscles: ["Rear Delts"], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Cable Reverse Fly", primaryMuscle: "Back", secondaryMuscles: ["Rear Delts"], category: "isolation", equipment: "cable", isCustom: false },
  // Shoulders
  { name: "Overhead Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps", "Upper Chest"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Dumbbell Shoulder Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Lateral Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], category: "isolation", equipment: "dumbbell", isCustom: false },
  { name: "Cable Lateral Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Front Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], category: "isolation", equipment: "dumbbell", isCustom: false },
  { name: "Arnold Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Upright Row", primaryMuscle: "Shoulders", secondaryMuscles: ["Traps"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Shoulder Press (Smith Machine)", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], category: "compound", equipment: "smith_machine", isCustom: false },
  { name: "Machine Shoulder Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], category: "compound", equipment: "machine", isCustom: false },
  { name: "Push Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps", "Legs"], category: "compound", equipment: "barbell", isCustom: false },
  // Arms
  { name: "Barbell Curl", primaryMuscle: "Biceps", secondaryMuscles: [], category: "isolation", equipment: "barbell", isCustom: false },
  { name: "Dumbbell Curl", primaryMuscle: "Biceps", secondaryMuscles: [], category: "isolation", equipment: "dumbbell", isCustom: false },
  { name: "Hammer Curl", primaryMuscle: "Biceps", secondaryMuscles: ["Brachialis"], category: "isolation", equipment: "dumbbell", isCustom: false },
  { name: "Preacher Curl", primaryMuscle: "Biceps", secondaryMuscles: [], category: "isolation", equipment: "barbell", isCustom: false },
  { name: "Cable Curl", primaryMuscle: "Biceps", secondaryMuscles: [], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Tricep Pushdown", primaryMuscle: "Triceps", secondaryMuscles: [], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Overhead Tricep Extension", primaryMuscle: "Triceps", secondaryMuscles: [], category: "isolation", equipment: "dumbbell", isCustom: false },
  { name: "Skull Crusher", primaryMuscle: "Triceps", secondaryMuscles: [], category: "isolation", equipment: "barbell", isCustom: false },
  { name: "Tricep Dip", primaryMuscle: "Triceps", secondaryMuscles: [], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Close-Grip Bench Press", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Close-Grip Bench Press (Smith Machine)", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], category: "compound", equipment: "smith_machine", isCustom: false },
  { name: "EZ-Bar Curl", primaryMuscle: "Biceps", secondaryMuscles: [], category: "isolation", equipment: "barbell", isCustom: false },
  { name: "Incline Dumbbell Curl", primaryMuscle: "Biceps", secondaryMuscles: [], category: "isolation", equipment: "dumbbell", isCustom: false },
  { name: "Concentration Curl", primaryMuscle: "Biceps", secondaryMuscles: [], category: "isolation", equipment: "dumbbell", isCustom: false },
  { name: "Spider Curl", primaryMuscle: "Biceps", secondaryMuscles: [], category: "isolation", equipment: "barbell", isCustom: false },
  { name: "Cable Hammer Curl", primaryMuscle: "Biceps", secondaryMuscles: ["Brachialis"], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Reverse Curl", primaryMuscle: "Biceps", secondaryMuscles: ["Forearms"], category: "isolation", equipment: "barbell", isCustom: false },
  { name: "Diamond Push-Up", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Cable Overhead Tricep Extension", primaryMuscle: "Triceps", secondaryMuscles: [], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Bench Dip", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "JM Press", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], category: "compound", equipment: "barbell", isCustom: false },
  // Legs
  { name: "Barbell Squat", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings", "Core"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Squat (Smith Machine)", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings", "Core"], category: "compound", equipment: "smith_machine", isCustom: false },
  { name: "Front Squat", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Leg Press", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], category: "compound", equipment: "machine", isCustom: false },
  { name: "Romanian Deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Back"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Romanian Deadlift (Smith Machine)", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Back"], category: "compound", equipment: "smith_machine", isCustom: false },
  { name: "Leg Curl", primaryMuscle: "Hamstrings", secondaryMuscles: [], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Lying Leg Curl (Machine)", primaryMuscle: "Hamstrings", secondaryMuscles: [], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Leg Extension", primaryMuscle: "Quads", secondaryMuscles: [], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Bulgarian Split Squat", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Hip Thrust", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Glute Bridge", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], category: "compound", equipment: "bodyweight", isCustom: false },
  { name: "Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Seated Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Hack Squat", primaryMuscle: "Quads", secondaryMuscles: ["Glutes"], category: "compound", equipment: "machine", isCustom: false },
  { name: "Lunges", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Sumo Deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Quads"], category: "compound", equipment: "barbell", isCustom: false },
  { name: "Goblet Squat", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Walking Lunge", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Step-Up", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], category: "compound", equipment: "dumbbell", isCustom: false },
  { name: "Cable Pull-Through", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], category: "compound", equipment: "cable", isCustom: false },
  { name: "Standing Calf Raise (Machine)", primaryMuscle: "Calves", secondaryMuscles: [], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Donkey Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Hip Adduction Machine", primaryMuscle: "Adductors", secondaryMuscles: [], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Hip Abduction Machine", primaryMuscle: "Abductors", secondaryMuscles: ["Glutes"], category: "isolation", equipment: "machine", isCustom: false },
  { name: "Cable Glute Kickback", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], category: "isolation", equipment: "cable", isCustom: false },
  // Core
  { name: "Plank", primaryMuscle: "Core", secondaryMuscles: [], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Crunch", primaryMuscle: "Core", secondaryMuscles: [], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Cable Crunch", primaryMuscle: "Core", secondaryMuscles: [], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Hanging Leg Raise", primaryMuscle: "Core", secondaryMuscles: ["Hip Flexors"], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Ab Wheel Rollout", primaryMuscle: "Core", secondaryMuscles: [], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Russian Twist", primaryMuscle: "Core", secondaryMuscles: [], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Side Plank", primaryMuscle: "Core", secondaryMuscles: ["Obliques"], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Bicycle Crunch", primaryMuscle: "Core", secondaryMuscles: ["Obliques"], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Sit-Up", primaryMuscle: "Core", secondaryMuscles: [], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "V-Up", primaryMuscle: "Core", secondaryMuscles: ["Hip Flexors"], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Dead Bug", primaryMuscle: "Core", secondaryMuscles: [], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  { name: "Cable Woodchopper", primaryMuscle: "Core", secondaryMuscles: ["Obliques"], category: "isolation", equipment: "cable", isCustom: false },
  { name: "Mountain Climbers", primaryMuscle: "Core", secondaryMuscles: ["Shoulders", "Cardio"], category: "bodyweight", equipment: "bodyweight", isCustom: false },
  // Cardio
  { name: "Treadmill", primaryMuscle: "Cardio", secondaryMuscles: [], category: "cardio", equipment: "machine", isCustom: false },
  { name: "Elliptical", primaryMuscle: "Cardio", secondaryMuscles: [], category: "cardio", equipment: "machine", isCustom: false },
  { name: "Stationary Bike", primaryMuscle: "Cardio", secondaryMuscles: [], category: "cardio", equipment: "machine", isCustom: false },
  { name: "Rowing Machine", primaryMuscle: "Cardio", secondaryMuscles: ["Back", "Arms"], category: "cardio", equipment: "machine", isCustom: false },
  { name: "Jump Rope", primaryMuscle: "Cardio", secondaryMuscles: [], category: "cardio", equipment: "none", isCustom: false },
  { name: "Battle Ropes", primaryMuscle: "Cardio", secondaryMuscles: ["Shoulders", "Arms"], category: "cardio", equipment: "none", isCustom: false },
  { name: "Stair Climber", primaryMuscle: "Cardio", secondaryMuscles: ["Legs"], category: "cardio", equipment: "machine", isCustom: false },
  { name: "Assault Bike", primaryMuscle: "Cardio", secondaryMuscles: ["Arms", "Legs"], category: "cardio", equipment: "machine", isCustom: false },
];
